### ISSUE TITLE
docs: Improve documentation and comments 

### ISSUE THREAD

**Issue by mithi** [mithi/bare-minimum-3d#19]
# Comments
It would be nice to have a description explaining the responsibility of each declared class/module
https://github.com/mithi/bare-minimum-3d/tree/master/src
<img width="278" alt="Screen Shot 2020-09-01 at 9 22 50 PM" src="https://user-images.githubusercontent.com/1670421/91856626-62cd6200-ec99-11ea-9b95-09f2151ab8f8.png">

# Documentation
Please check the [wiki / documentation](https://github.com/mithi/bare-minimum-3d/wiki), to learn the arguments that you'll need to pass to `BareMinimum3d`'s `renderScene` function. 
- [`SceneOptions`](https://github.com/mithi/bare-minimum-3d/wiki/SceneOptions)
- [`SceneSettings`](https://github.com/mithi/bare-minimum-3d/wiki/SceneSettings)
- [`ViewSettings`](https://github.com/mithi/bare-minimum-3d/wiki/ViewSettings)

**Comment by BertinoCanisius** [comment]
Hi . I would like to contribute for this.

**Comment by mithi** [comment]
> Hi . I would like to contribute for this.

Sure! Thank you for your interest! 
Don't forget to read the [contributing guidelines](https://github.com/mithi/hexapod/blob/master/CONTRIBUTING.md) and the recommended [commit style guide](https://github.com/mithi/hexapod/wiki/A-Commit-Style-Guide)! Thank you!

And let me know if you have any questions!

**Comment by BertinoCanisius** [comment]
I couldnt push my changes to my branch. It says permission denied.
Can you help me with this? Sorry I am new to this

**Comment by mithi** [comment]
what did you try to do so far ?

**Comment by mithi** [comment]
> I couldnt push my changes to my branch. It says permission denied.
> Can you help me with this? Sorry I am new to this

You can try following the steps here: https://github.com/mithi/hexapod/wiki/Simple-Git-Workflow-guide
